### ISSUE TITLE
When you run the delete_bluecompute_ce.sh script, it should take you back to a clean state.

### ISSUE THREAD

**Issue by DevOps-GM** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#14]
Currently when you run the delete_bluecompute_ce.sh script, several jobs are left in Kubernetes.  These should be deleted when the script runs with the ultimate goal to be left in a state as if you have never installed when you execute the delete script.

**Comment by fabiogomezdiaz** [comment]
Since Kubernetes has a bug, we cannot really delete the container unless it's done manually on the dashboard. So we added random characters to the job names to prevent name coalition.

Basically, you can delete bluecompute and reinstall it without interference from uncleaned artifacts.

Closing for now. Please reopen if getting the same issue. Else, open a new issue.

Fixed by a86ffb2

**Comment by DevOps-GM** [comment]
It is good that you have fixed half of the problem so that you can actually get the uninstall script to run successfully.  However, the readme file must explain to people that  your Kubernetes may still have leftover artifacts and provide instructions on how to remove the things that are left over.
