### ISSUE TITLE
Fix the Bluecompute sample so that the login works correctly the first time.

### ISSUE THREAD

**Issue by DevOps-GM** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#15]
When you login to the Bluecompute application using the URL that you receive after the install, the login fails the first time.  IT works successfully using the same credentials the second time you try to log in.  This needs fixed.

**Comment by fabiogomezdiaz** [comment]
@DevOps-GM our installation and validation instructions have changed dramatically since this issue was created. Here is a link to instructions:
https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes#deploy-the-application

Closing this issue for now. Please note that it takes all the microservices 5-10 minutes to be fully initialized and ready. If still having issues after waiting, then please open a separate issue.
