### ISSUE TITLE
Feedback for consideration on Reference Implementation 

### ISSUE THREAD

**Issue by rjminsha** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#24]
Nice reference implementation! 

Few thoughts on the current reference implementation
- For the projects (auth etc) there is a combination of Travis and Jenkins being used.  Wonder if the .travis.yaml should/could be used consistently to aid in people cloning.  Also would like to see testing of charts to a tmp namespace in a cluster added to .travis.yaml.  
-  Individual Charts could include tests in templates (https://github.com/kubernetes/helm/blob/master/docs/chart_tests.md)
- Perhaps a Provide starter Kit for Helm as a deliverable 
- Is there a reason to install all the Charts individually rather than parent chart with requirements.yaml ?
- Chart install scripts should probably include namespace

Also maybe good to have protected master, PRs and squashed commits to keep the git history clean for outside viewers and contributors.

**Comment by fabiogomezdiaz** [comment]
@rjminsha thanks for your valuable feedback. We have changed our instructions dramatically and deliverables dramatically since this issue was opened. Feel free to check the assets again and provide new feedback. Here is an answer to some of the comments you posted"

**- For the projects (auth etc) there is a combination of Travis and Jenkins being used.  Wonder if the .travis.yaml should/could be used consistently to aid in people cloning.  Also would like to see testing of charts to a tmp namespace in a cluster added to .travis.yaml.** 
We have since moved to using Jenkinsfile primarily for CICD scenarios and encourage people to use their existing Jenkins deployment. For new Jenkins deployments, we have assets that show you how to deploy Jenkins inside your kubernetes cluster. Those assets can be found [here](https://github.com/ibm-cloud-architecture/refarch-cloudnative-devops-kubernetes)

**-  Individual Charts could include tests in templates (https://github.com/kubernetes/helm/blob/master/docs/chart_tests.md)**
This is a great suggestion! Had no idea this existed as part of helm. Will take this into consideration moving forward.

**- Perhaps a Provide starter Kit for Helm as a deliverable**
Not sure what you mean by this. So I am going to interpret it as perhaps you wanting an asset to help you install helm. If so, we actually point to the official helm documentation to install helm as pointed out [here](https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes#download-required-clis)

**- Is there a reason to install all the Charts individually rather than parent chart with requirements.yaml?**
We have since updated our project to use a master umbrella chart that has all the projects as dependencies. Check it out [here](https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes#deploy-to-kubernetes-cluster). 

**- Chart install scripts should probably include namespace**
We no longer use those scripts as we rely primarily on installing the chart as instructed in the link above. For different namespaces though, we have extra steps to be taken before installing the chart, as laid out [here](https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/blob/master/PodSecurityPolicy/PodSecurityPolicy.md)

**Also maybe good to have protected master, PRs and squashed commits to keep the git history clean for outside viewers and contributors.**
We have since abandoned the multiple branch approach and adopted the Fork & Pull model for master branch. We do need to add contributing guidelines though

Anyways, I hope this helps. Closing this issue for now. If you have any other feedback or encounter problems with this repo, please feel free to open another issue.
