### ISSUE TITLE
After deploying to bluemix successfully, can't access the app from browser

### ISSUE THREAD

**Issue by wangzhidong** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#35]
![temp](https://user-images.githubusercontent.com/9131685/29595018-6cef9b00-87e7-11e7-8f64-c0117c4f6c02.png)

But when I try to access http://10.127.239.96:30289/ from browser, get the following error:

Network Error (tcp_error)
--
A communication error occurred: "Connection refused"
The Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time.

**Comment by avina-z** [comment]
I am getting this same error, was this resolved?

**Comment by fabiogomezdiaz** [comment]
@wangzhidong and @avina-z  we have since provided new installation instructions as well as new instructions for obtaining Web UI IP Address upon installing the chart. Instructions are here:
https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes#deploy-to-kubernetes-cluster

Closing the issue for now, please reopen if still having the same issues. Else, please open a new issue.
