### ISSUE TITLE
Bluecompute WebUI public IP address missing in output of installation 

### ISSUE THREAD

**Issue by vksinghibm** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#37]
The output of command
./install_bluecompute_ce.sh vinodtest2cluster cloudnative-dev <bluemixapiakey> 
Finally, on another browser window, copy and paste the following URL for BlueCompute Web UI:
http://10.76.92.201:31817

Provides private IP address of worker node

**Comment by vksinghibm** [comment]
I did the "dirty" fix for my lite cluster with single node:

Old code :#       nodeip=$(kubectl get nodes -o jsonpath='{.items[*].status.addresses[?(@.type=="ExternalIP")].address}' | awk '{print $1}')

 New code:       nodeip=$(bx cs workers ${CLUSTER_NAME} | sed -n '7p'| awk '{print $2}')

**Comment by fabiogomezdiaz** [comment]
@vksinghibm we have since provided new installation instructions as well as new instructions for obtaining Web UI IP Address. Instructions are here:
https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes#deploy-to-kubernetes-cluster

Closing the issue for now, please reopen if still having the same issues. Else, please open a new issue.
