### ISSUE TITLE
Bluecompute ce V0.0.6 does not work on ICP 2.1.0.2 or 2.1.0.3

### ISSUE THREAD

**Issue by pdfruth** [ibm-cloud-architecture/refarch-cloudnative-kubernetes#84]
Upon installing the latest version of the Bluecompute CE chart (currently V0.0.6), attempting to access the application at http://ip:31337/bluecompute the front page is rendered.
Upon clicking the "Browse" catalog button, a blank page is displayed and the application is unusable.

**Comment by pdfruth** [comment]
I have been doing some additional testing with the bluecompute-ce application.
The problem only appears to happen when the helm chart is installed into a namespace other than the "default" namespace.
When it's installed into a non-default namespace, I see that all the "bluecompute-catalog-elasticsearch" deployment does not become active.
Attempts to access the bluecompute catalog, at http://x.x.x.x:31337/#!/catalog, results in a blank screen initially, then broken links for images after some time.

**Comment by osowski** [comment]
The issue here is related to some of the requirements needed for the container image used in the Elasticsearch chart to run in a non-default namespace.  If you run a `kubectl describe replicaset {name}-catalogdb-elasticsearch-{XYZ}`, you will see the following under **Events**: `unable to validate against any pod security policy: [capabilities.add: Invalid value: "IPC_LOCK": capability may not be added]`.

To rectify this issue, you can run the following command to add the `privileged` PodSecurityPolicy to the service account that is created in your new namespace by default. 

`kubectl create rolebinding -n <namespace> rolebindingname --clusterrole=privileged --serviceaccount=<namespace>:default`.

After creating this rolebinding, you can either scale the replicaset down to 0 and then back to 1 for it be created successfully, or use `helm` to redeploy the entire stack *(depending on your preference)*.

I will update the documentation to reflect this need for rolebinding when deploying in a non-default namespace.
